version: "3.8"

services:
  pearserver:
    build: ./pearserver
    image: pearstock/pearserver:latest
    container_name: pearserver
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: ${BACKEND_SECRET_KEY}
      ALLOWED_HOSTS: ${BACKEND_ALLOWED_HOSTS}
      CORS_ALLOWED_ORIGINS: ${BACKEND_CORS_ALLOWED_ORIGINS}

  webclient:
    build: ./webclient
    image: pearstock/webclient:latest
    container_name: webclient
    ports:
      - "3000:3000"
    depends_on:
      - pearserver
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
